--- 
- 
  hosts: all
  name: "Deploy Postfix"
  environment:
    PYTHONPATH: "/home/path/.local/lib/python2.7/site-packages"
  tasks:
    - name: Install required system packages
      yum: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
      
  ,- name: Install Docker Module for Python
      pip:
        name: docker
        
    - name: Pull postfix container from Docker Hub and Deploy
      docker_container: 
        env: 
          ALLOWED_SENDER_DOMAINS: "example.com example.org"
          MYNETWORKS: 192.168.178.0/24
        image: boky/postfix
        name: postfix
        ports: 
          - "587:587"
        pull: yes

