--- 
- 
  hosts: all
  name: "Deploy Postfix"
  tasks: 
    - 
      docker_container: 
        env: 
          ALLOWED_SENDER_DOMAINS: "example.com example.org"
          MYNETWORKS: 192.168.178.0/24
        image: boky/postfix
        name: postfix
        ports: 
          - "587:587"
        pull: yes
        state: reloaded
      name: "Create a Docker Container"

