--- 
- hosts: all
  
  name: "Deploy Postfix"
  tasks:
    - name: Install required system packages
      yum: name={{ item }} state=latest update_cache=yes
      loop: [ 'ca-certificates', 'curl', 'python3-pip', 'python3-setuptools', 'python-virtualenv', 'epel-release', 'python-pip']
      
    - name: Install Docker Module for Python
      pip:
        name: docker
        
    - name: Pull postfix container from Docker Hub and Deploy
      docker_container: 
        env: 
          ALLOWED_SENDER_DOMAINS: "example.com example.org"
          MYNETWORKS: 192.168.178.0/24
        image: boky/postfix
        name: postfix
        ports: 
          - "587:587"
        pull: yes
